version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test: # this can be any name you choose
    context: BEARER_TOKEN_TWITTER_CORE_APP
    executor: python/default
      
      
    
    steps:
      - checkout

      - run:
          name: "echo an env var that is part of our context"
          command: |
            echo $BEARER_TOKEN      

      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          env:
            BEARER_TOKEN: ${{BEARER_TOKEN}}
          command: python3 tw_core_app.py 
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  
workflows:
  testpass:
    jobs:
      - build_and_test
    